### ISSUE TITLE
Error in forwardbackward() function while training the data 

### ISSUE THREAD

**Issue by hardik2396** [batra-mlp-lab/visdial#14]
After setting up dependencies, on execution of  `th train.lua -encoder lf-ques -decoder gen -gpuid 0
`  error as shown in the snapshot below, is raised. I tried on the different PC configurations and the error still persists hence it is not a system specific problem. 
![image](https://user-images.githubusercontent.com/25536397/32011440-6e2fbbe0-b9d2-11e7-81bd-238efbc52da2.png)

**Comment by interritus1996** [comment]
I got the same error. I think the error occurs due to change in the module of rnn installed by LuaRocks. Recently, the previous module (https://github.com/Element-Research/rnn) has been deprecated and the new module (https://github.com/torch/rnn) is being used. Try to install the deprecated module and I guess this error will not occur.

## Installation steps
``` 
git clone https://github.com/Element-Research/rnn.git
cd rnn
luarocks make rocks/rnn-scm-1.rockspec
```
